--- 
# Ubuntu specific variables

package_mgr: apt

# Postgresql dependencies
postgres_dependencies:
  - libpq-dev
  - libssl-dev
  - sysstat


# Extra
postgres_extra:
  - "postgresql-contrib-{{ postgres_version }}"
  - "postgresql-{{ postgres_version }}-postgis-{{ postgis_version }}"
  - python3-psycopg2

# Postgres package name
postgres_package: "postgresql-{{ postgres_version }}"

# Postgresql init name
postgres_init_name: "postgresql"

# repos
postgres_repo_key: "https://www.postgresql.org/media/keys/ACCC4CF8.asc "

postgres_repo_url: "http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

postgres_repo_dest: "/etc/apt/sources.list.d/pgdg.list"

# Configuration files path
postgres_conf_base_dir: "/etc/postgresql"

postgres_conf_file: "{{ postgres_conf_base_dir }}/{{ postgres_version }}/main/postgresql.conf"
postgres_hba_file: "{{ postgres_conf_base_dir }}/{{ postgres_version }}/main/pg_hba.conf"
postgres_ident_file: "{{ postgres_conf_base_dir}}/{{ postgres_version }}/main/pg_ident.conf"

# Data dir
postgres_data_dir: "/var/lib/postgresql/{{ postgres_version }}/main"
