---

# Os specific variables 
- name : Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

# OS neutral variables
- include_vars: "default.yml"

# Include installation tasks
- import_tasks: install.yml

# Include configuration tasks
- import_tasks: configure.yml
